version: '3.8'

services:
  web:
    platform: linux/amd64
    build: .
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - ./.vscode:/app/.vscode
    environment:
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
    command: tail -f /dev/null
    env_file:
      - .env
