name: Link

on:
  push:
    'branches':
      - '**'


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          pip install ruff==0.1.1
      - name: Lint
        run: |
          make lint
      