name: Link

on:
  push:
    'branches':
      - '**'


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get install -y make
      - name: Lint
        run: |
          make lint
      